第6回課題
Ryo802701/RaiseTechJavaEx6 pull request #1
Opened 2022-08-26 13:24 UTC by Ryo802701

①http://locathost:8080/helloworld/1
「Hello World!」を表示。

②http://locathost:8080/helloworld/2
「Hello World!!」と現在時刻の２行を表示したかったのでHTMLでしました。

③http://locathost:8080/helloworld/3
chromeであれば「設定」の「言語」で希望の言語を「トップに移動」でリクエストに含まれるLocaleが変わり、
Localeに応じたmessage_XX.propertiesからメッセージを取得して表示します。

課題内容を検索すると「国際化」とか「多言語対応」という単語が出てきて、以下のサイトを参考にしました。
（課題の意図だったかわかりませんが）
https://qiita.com/nulltemp/items/12d9c071da9e450e5eb8
（このページに書いてある通り、Localeに対応するファイルが見つからない場合、デフォルトファイル(messages.properties)
を見に行かず、messages_jp.propertiesの内容が表示されるので「対策」の内容を実装する必要があるとのことです。。）

2022-08-30 04:51 UTC, YudaiNoda3576 requested changes
コメントしています〜！
遅くなりましてすみません😅

2022-08-30 04:51 UTC, YudaiNoda3576 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +@RestController
`＠RestController`と`@Controller`とアノテーションが二種類あるので、それぞれ調べてみて頂いて、
今回はどちらが適切か考えてみてください~!

2022-08-30 04:51 UTC, YudaiNoda3576 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +    @Autowired
アノテーションで依存関係を注入するよりもコンストラクタ形式で依存関係を注入するのが推奨されてますので、修正のほどよろしくお願いします〜！

2022-08-30 04:51 UTC, YudaiNoda3576 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +	public String hello1() {
ここはインデントが崩れてるのが気になりますね〜
IDEの設定で保存時にインデントを修正するみたいなことができるので設定してみてください！

2022-08-30 04:51 UTC, YudaiNoda3576 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +		res.setContentType("text/html; charset=Shift_JIS");
htmlをバックエンドからビューに直接流すみたいなこともしなくは無いんですが、
あまりおすすめは出来ないです。

と言うのもHTMLの生成がバックエンドの責務が広くなってしまっていてバックエンドとフロントエンドの役割の住み分けが曖昧になってしまうからです。
そうなると、後々保守が大変だったり、思わぬバグが発生したりします。

また、今回で言うとControllerに記載されていますが、これもControllerの責務から外れているように感じます。
もしやるならServiceクラスなどに分離させてHTMLを生成するメソッドに切り分けたほうが良いです。
こうして細かくメソッドやクラスを分離しておくと後々テストもしやすくなります！

余裕があればで大丈夫ですが、、、
バックエンドでHTMLを生成せずにJava側でHTMLファイルを別途作成してそれを表示することが可能で、そちらのほうが主流のためHTMLファイルを別途作成してそこに文字列と時間を表示するように実装を変更してみてください〜！

2022-08-31 02:40 UTC, Ryo802701 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +@RestController
以下調べました。

・@Controller
Webページ（HTML）を返す際に使用する。
戻り値としてView名を指定することでthymeleafなどで生成された<View名>.htmlを表示する。

・@RestController
主にJSON（やXML）などでリソースを返す際に使用する。
戻り値にオブジェクトを指定すると、Spring BootがJacksonを使ってJSON形式に変換してくれる。
（XMLの場合はあまり情報がありませんでしたがコンテンツタイプに"application/xml"を指定するか、ライブラリjackson-dataformat-xmlを追加する必要がある？）
HTTPステータスやレスポンスヘッダを指定したい時は、戻り値をResponseEntityにする。
（@Controllerでもメソッドに@ResponseBodyを指定することで@RestControllerと同じことができる。）

今回は「Hello World」を画面に表示するという課題でしたが、
動画内の実演で@RestControllerを使われていたのと、Viewについては触れられていなかったという理由で
@RestControllerを使用しました。
単に画面に表示するという観点でいくと@Controllerの方が適切だったでしょうか？
（何らかのリソースにアクセスして「Hello World」という文字列を取得したという観点だと@RestController？）

2022-08-31 02:54 UTC, Ryo802701 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +	public String hello1() {
すみません。上げる前に整形する癖を付けたいと思います。

2022-08-31 03:03 UTC, Ryo802701 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +		res.setContentType("text/html; charset=Shift_JIS");
>Controllerの責務から外れているように感じます。
言われてみればその通りですね。MVCの原則からも外れています。

上でも触れましたが、第６回内でHTML（View）に（まだ？）触れられていなかったので、
HTMLファイルを使わずに複数行表示したいと調べて取った方法でした。。

2022-08-31 12:17 UTC, Ryo802701 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +    @Autowired
↑上記内容を検索したところ、コンストラクタインジェクションというワードが出てきましてそれを参考に
コンストラクタでDIしました。
修正内容合っていますでしょうか。
（@Autowired省略できるのですね。）

2022-09-01 02:23 UTC, YudaiNoda3576 reviewed
コメントだけしてますので確認したら、
マージしてください！

![LGTM](https://image.lgtmoon.dev/179567)

2022-09-01 02:23 UTC, YudaiNoda3576 commented on src/main/java/com/example/RaiseTechJavaEx6/HelloWorldController.java
> +@RestController
かなり詳細に調べていただきありがとうございます！
XMLについてはあまり使われる機会は無くなってきている（レガシーなシステムだとあるかもです）ので基本的にレスポンスはJSONで返すと思っておいてもらっても良いかもです。

今回はHTMLファイルを別途作成頂いたので、`@Controller` を使用すれば良いかなと思います（実演で`@RestController`を使用していたことを知らず、混乱させてしまい申し訳ないです）
`@RestController`を使用してJavaはAPIとして実装し、VueやReactなどのフロントエンドにJSONデータを返却し、画面に表示するというBFFというアーキテクチャでよく使用されると思いますので知識として知っておいてください〜

2022-09-01 11:47 UTC, merged